apiVersion: v2
name: cloudsql-proxy
version: 2.0.3
appVersion: "1.16"
description: Google Cloud SQL Proxy
keywords:
- google
- cloud
- postgresql
- mysql
- sql
- sqlproxy
home: https://cloud.google.com/sql/docs/postgres/sql-proxy
engine: gotpl
