{{- if gt .Values.replicaCount 1.0 -}}
{{- if and (.Capabilities.APIVersions.Has "policy/v1") (semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion) -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ include "cloudsql-proxy.fullname" . }}
  labels:
    {{ include "cloudsql-proxy.labels" . | indent 4 | trim }}
spec:
  selector:
    matchLabels:
      {{ include "cloudsql-proxy.selector" . | indent 6 | trim }}
  maxUnavailable: {{ if .Values.maxUnavailable }}{{ .Values.maxUnavailable }}{{- else }}{{ ceil (div .Values.replicaCount 2) }}{{- end }}
{{- end -}}
