{{- if .Values.tasks.backup.cron -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mysql-backup.fullname" . }}
  labels:
    {{ include "mysql-backup.labels" . | indent 4 | trim }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
        {{- if .Values.image.pullSecrets }}
          imagePullSecrets:
          {{- range .Values.image.pullSecrets }}
            - name: {{ . }}
          {{- end }}
        {{- end }}
          restartPolicy: Never
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["sh", "-c", "/scripts/mysql-backup.sh"]
            env:
            - name: DB_HOST
              value: {{ .Values.database.host }}
            - name: DB_NAME
              value: {{ .Values.database.name }}
            - name: DB_CHARSET
              value: {{ .Values.database.charset }}
            - name: GSBUCKET
              value: {{ .Values.gcs.bucket.name }}
            - name: GSPATH
              value: {{ .Values.gcs.bucket.path }}
            - name: FILENAME
              value: {{ include "mysql-backup.filename" . }}
            envFrom:
            - secretRef:
                name: {{ include "mysql-backup.fullname" . }}-mysql
            resources:
{{ toYaml .Values.resources | indent 14 }}
            volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: secret-key
              mountPath: /etc/gcloud
              readOnly: true
          volumes:
          - name: scripts
            configMap:
              name: {{ include "mysql-backup.fullname" . }}
              defaultMode: 0555
          - name: secret-key
            secret:
              secretName: {{ include "mysql-backup.fullname" . }}-gcs
{{- end -}}
